### ISSUE TITLE
Could a release be cut for Scala 2.11? :)

### ISSUE THREAD

**Issue by vergenzt** [emchristiansen/PersistentMap#6]
This appears to be *incredibly* useful, but the project I need it for is compiling on Scala 2.11. :/ I'd be happy to try to do this myself but I'm pretty unfamiliar with sbt (I use Gradle for my projects). If you're too busy could you maybe point me in the right direction?

**Comment by emchristiansen** [comment]
Will do.

**Comment by vergenzt** [comment]
Thanks so much. This repo is perfect for what I need.

**Comment by emchristiansen** [comment]
It looks like a couple of the libraries I depend on have had API-breaking changes since I last updated this project.
So it might be a day or so before the update is complete.

**Comment by vergenzt** [comment]
However long it takes is fine; I'm in no rush.

**Comment by vergenzt** [comment]
If you're particularly busy or don't want ti work on it, I wouldn't mind starting on a pull request for this tomorrow.

**Comment by emchristiansen** [comment]
I've quashed most of the build errors, so I think I'll have something today.
I'll let you know if I get stuck or slowed down.

**Comment by vergenzt** [comment]
Cool! Thanks.

**Comment by emchristiansen** [comment]
Done!
The new artifact is 0.1.3-SNAPSHOT.

**Comment by vergenzt** [comment]
Awesome! Does the new release have the most recent versions of all the
dependencies (i.e. Slick 2.something, etc) or is Scala the only version
change? Thanks so much!

**Comment by emchristiansen** [comment]
It should have the newest versions of all the libraries.
For Slick, it's 2.x, not 3.x RC, because I didn't want to learn their new interface right now.

**Comment by vergenzt** [comment]
I can't get an example to work. The type that `PersistentMap.create` expects is `scala.slick.jdbc.JdbcBackend.Database`, but I only seem to be able to get a `scala.slick.jdbc.DatabaseDef`, e.g. through:

```
import scala.slick.driver.JdbcDriver.simple._
val db = Database.forURL(url, driver=driver)
```

**Comment by vergenzt** [comment]
Any thoughts?

**Comment by emchristiansen** [comment]
Can you just adapt the tests?
E.g., here I'm creating a Database:
https://github.com/emchristiansen/PersistentMap/blob/master/src/test/scala/st/sparse/persistentmap/testPersistentMap.scala#L27

**Comment by vergenzt** [comment]
Oh, duh. Sorry, didn't occur to me. Thanks.
